name: build

on:
  push:
    branches:
      - netskope

  pull_request:

  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry-Run'
        default: 'true'
        required: false

env:
  # Currently no way to detect automatically (#8153)
  DEFAULT_BRANCH: netskope
  NODE_VERSION: 14
  DRY_RUN: false

jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ["self-hosted", "linux", "x64", "bazel"]
    # release shouldn't need more than 5 min
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: calculate-the-version
        id: ep_versioner
        run: |
          PLATFORM=$(echo $(uname -s)_$(uname -m) | tr '[:upper:]' '[:lower:]')
          VERSIONER_VERSION=22.90.205
          VERSIONER_DIR=ep-tools/ep-versioner/$VERSIONER_VERSION/$PLATFORM
          VERSIONER=$VERSIONER_DIR/ep-versioner
          mkdir -p .$VERSIONER_DIR
          curl -o .$VERSIONER https://artifactory-rd.netskope.io/artifactory/$VERSIONER
          chmod 755 .$VERSIONER
          EP_RENOVATE_VERSION=$(.$VERSIONER calc)
          echo EP_RENOVATE_VERSION=$EP_RENOVATE_VERSION
          echo "::set-output name=EP_RENOVATE_VERSION::$EP_RENOVATE_VERSION"

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Clone docker-renovate
        run: git clone https://github.com/renovatebot/docker-renovate

      - name: fix Dockerfile
        run: |
          sed -i 's|yarn version --new-version ${RENOVATE_VERSION}|yarn version --new-version ${RENOVATE_VERSION} --no-git-tag-version|' docker-renovate/Dockerfile
          sed -i 's|COPY bin/ /usr/local/bin/||' docker-renovate/Dockerfile

      - name: Docker build
        run: docker build . -f docker-renovate/Dockerfile\
          -t artifactory.netskope.io/ep-tools-docker/instruments/renovate-slim:$TAG
        env:
          TAG: ${{ steps.ep_versioner.outputs.EP_RENOVATE_VERSION}}
      
      - name: Docker push
        run: |
          docker login --username ${NS_ARTIFACTORY_USER} --password ${NS_ARTIFACTORY_PASSWORD} artifactory.netskope.io
          docker push artifactory.netskope.io/ep-tools-docker/instruments/renovate-slim:$TAG
        env:
          NS_ARTIFACTORY_PASSWORD: ${{secrets.NS_ARTIFACTORY_PASSWORD_LIMITED}}
          NS_ARTIFACTORY_USER: ${{secrets.NS_ARTIFACTORY_USER_LIMITED}}
          TAG: ${{ steps.ep_versioner.outputs.EP_RENOVATE_VERSION}}
