name: build

on:
  push:
    branches:
      - netskope

  pull_request:

  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry-Run'
        default: 'true'
        required: false

env:
  # Currently no way to detect automatically (#8153)
  DEFAULT_BRANCH: netskope
  NODE_VERSION: 14
  DRY_RUN: false

jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ["self-hosted", "linux", "x64", "bazel"]
    # release shouldn't need more than 5 min
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build ${{ env.NPM_VERSION }}
        run: yarn build

      - name: semantic-release
        run: echo "Not pushing to npm yet"

        # run: |
        #   echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ./.npmrc
        #   npx semantic-release --dry-run ${{env.DRY_RUN}}
        #   git checkout -- .npmrc
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Upload docs
      #   uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
      #   with:
      #     name: docs
      #     path: tmp/docs/
