name: Netskope Build

on:
  push:
    branches:
      - team/netskope@main

  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  release:
    runs-on: ['self-hosted', 'linux', 'x64', 'rg-default', 'sz-L']

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: calculate-the-version
        id: ep_versioner
        run: |
          PLATFORM=$(echo $(uname -s)_$(uname -m) | tr '[:upper:]' '[:lower:]')
          VERSIONER_VERSION=23.92.205
          VERSIONER_DIR=ep-tools/ep-versioner/$VERSIONER_VERSION/$PLATFORM
          VERSIONER=$VERSIONER_DIR/ep-versioner
          mkdir -p .$VERSIONER_DIR
          curl -o .$VERSIONER https://artifactory-rd.netskope.io/artifactory/$VERSIONER
          chmod 755 .$VERSIONER
          EP_RENOVATE_VERSION=$(.$VERSIONER calc --deepen --format triple)
          echo EP_RENOVATE_VERSION=$EP_RENOVATE_VERSION
          echo "::set-output name=EP_RENOVATE_VERSION::$EP_RENOVATE_VERSION"

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clone docker-renovate
        run: |
          git clone https://github.com/renovatebot/docker-renovate
          cd docker-renovate
          git reset --hard 5da5ad37dec846546ea7d7fb529b97270b8f6026

      - name: fix Dockerfile
        run: |
          sed -i 's|16.19.0|20.6.1|' docker-renovate/Dockerfile
          sed -i 's|yarn version --new-version ${RENOVATE_VERSION}|yarn version --new-version ${RENOVATE_VERSION} --no-git-tag-version|' docker-renovate/Dockerfile
          sed -i 's|COPY bin/ /usr/local/bin/||' docker-renovate/Dockerfile

      - name: Docker build
        run: |
          docker build . -f docker-renovate/Dockerfile \
            -t artifactory.netskope.io/ep-tools-docker/instruments/renovate-slim:$TAG
        env:
          TAG: ${{ steps.ep_versioner.outputs.EP_RENOVATE_VERSION}}

      - name: Docker push
        run: |
          docker login --username ${NS_ARTIFACTORY_USER} --password ${NS_ARTIFACTORY_PASSWORD} artifactory.netskope.io
          docker push artifactory.netskope.io/ep-tools-docker/instruments/renovate-slim:$TAG
        env:
          NS_ARTIFACTORY_PASSWORD: ${{secrets.NS_ARTIFACTORY_PASSWORD_LIMITED}}
          NS_ARTIFACTORY_USER: ${{secrets.NS_ARTIFACTORY_USER_LIMITED}}
          TAG: ${{ steps.ep_versioner.outputs.EP_RENOVATE_VERSION}}
